#!/usr/bin/env node
/**
 * IBAN Registry Builder
 *
 * Parses the newest SWIFT IBAN Registry TXT file in this folder and generates
 * src/countries/registry.ts with the values the registry defines.
 *
 * Usage:
 *   npm run registry          (runs this script and formats the output)
 *   node registry/builder.mjs [--output path]
 *
 * Options:
 *   --output path   Output file path (default: src/countries/registry.ts)
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Parse command line arguments
const args = process.argv.slice(2);
let outputPath = path.join(__dirname, '..', 'src', 'countries', 'registry.ts');

for (let i = 0; i < args.length; i++) {
  if (args[i] === '--output' && args[i + 1]) {
    outputPath = args[i + 1];
    i++;
  }
}

/**
 * Convert BBAN structure notation to regex, merging adjacent fields of the same type
 * e.g., "4!n4!n12!c" -> "^[0-9]{8}[A-Z0-9]{12}$"
 */
function structureToRegex(structure) {
  const runs = [];
  for (const [, amount, type] of structure.matchAll(/(\d+)!(.)/g)) {
    let range = '[A-Z0-9]';
    if (type === 'n') range = '[0-9]';
    else if (type === 'a') range = '[A-Z]';
    const last = runs.at(-1);
    if (last && last.range === range) last.amount += parseInt(amount, 10);
    else runs.push({ range, amount: parseInt(amount, 10) });
  }
  return `^${runs.map(({ range, amount }) => `${range}{${amount}}`).join('')}$`;
}

/**
 * Find the latest iban-registry-vXXX.txt file in the registry folder
 */
function findLatestRegistry() {
  const files = fs.readdirSync(__dirname);
  const registryFiles = files
    .filter((f) => /^iban-registry-v\d+\.txt$/.test(f))
    .sort((a, b) => {
      const versionA = parseInt(a.match(/v(\d+)/)[1], 10);
      const versionB = parseInt(b.match(/v(\d+)/)[1], 10);
      return versionB - versionA; // Descending order (latest first)
    });

  if (registryFiles.length === 0) {
    throw new Error('No iban-registry-vXXX.txt file found in registry folder');
  }

  return path.join(__dirname, registryFiles[0]);
}

/**
 * Parse SWIFT TXT registry file
 */
function parseRegistry(txtPath) {
  console.log(`Using: ${path.basename(txtPath)}`);

  const rawContent = fs.readFileSync(txtPath, 'latin1');

  // Join lines that are continuations (handle quoted multi-line values)
  const lines = [];
  let currentLine = '';

  for (const line of rawContent.split('\n')) {
    if (line.startsWith('"\t') && currentLine) {
      currentLine += line.slice(1);
    } else {
      if (currentLine) {
        lines.push(currentLine);
      }
      currentLine = line;
    }
  }
  if (currentLine) {
    lines.push(currentLine);
  }

  const result = [];

  lines.forEach((line) => {
    const data = line.split('\t').map((e) => e.trim().replace(/^"|"$/g, ''));
    const key = data[0];
    const values = data.slice(1);

    if (key === 'Name of country') {
      values.forEach((el, i) => {
        result[i] = { country_name: el };
      });
    }
    if (key === 'IBAN prefix country code (ISO 3166)') {
      values.forEach((el, i) => {
        if (result[i]) result[i].code = el;
      });
    }
    if (key === 'SEPA country') {
      values.forEach((el, i) => {
        if (result[i]) result[i].sepa = el === 'Yes';
      });
    }
    if (key === 'IBAN length') {
      values.forEach((el, i) => {
        if (result[i]) result[i].length = parseInt(el, 10);
      });
    }
    if (key === 'BBAN structure') {
      values.forEach((el, i) => {
        if (result[i]) {
          result[i].bban_regexp = structureToRegex(el);
        }
      });
    }
    if (key === 'Bank identifier position within the BBAN') {
      values.forEach((el, i) => {
        if (result[i] && el !== 'N/A' && el !== '') {
          const parts = el.split('-').map((n) => parseInt(n, 10) - 1);
          result[i].bank_identifier = parts.join('-');
        }
      });
    }
    if (key === 'Branch identifier position within the BBAN') {
      values.forEach((el, i) => {
        if (result[i] && el !== 'N/A' && el !== '') {
          const parts = el.split('-').map((n) => parseInt(n, 10) - 1);
          result[i].branch_indentifier = parts.join('-');
        }
      });
    }
    if (key === 'IBAN electronic format example') {
      values.forEach((el, i) => {
        if (result[i]) result[i].iban_example = el;
      });
    }
  });

  return result.filter((s) => s.code).sort((a, b) => a.code.localeCompare(b.code));
}

/**
 * Generate src/countries/registry.ts content
 */
function generateOutput(specs, registryFile) {
  let output = `// Generated by registry/builder.mjs from ${registryFile}. Do not edit; run \`npm run registry\` instead.\n\n`;
  output += "import { type CountryMapInternal } from '../core/types';\n\n";
  output += '/** Country specifications as defined by the SWIFT IBAN Registry. */\n';
  output += 'export const registrySpecs: CountryMapInternal = {\n';

  specs.forEach((spec) => {
    output += `  ${spec.code}: {\n`;
    output += `    chars: ${spec.length},\n`;
    output += `    bban_regexp: '${spec.bban_regexp}',\n`;
    output += `    IBANRegistry: true,\n`;
    if (spec.sepa) {
      output += `    SEPA: true,\n`;
    }
    if (spec.bank_identifier) {
      output += `    bank_identifier: '${spec.bank_identifier}',\n`;
    }
    if (spec.branch_indentifier) {
      output += `    branch_indentifier: '${spec.branch_indentifier}',\n`;
    }
    output += '  },\n';
  });

  output += '};\n';
  return output;
}

// Main
console.log('IBAN Registry Builder');
console.log('');

const registryPath = findLatestRegistry();
const specs = parseRegistry(registryPath);
console.log(`Parsed ${specs.length} countries`);

const output = generateOutput(specs, path.basename(registryPath));
fs.writeFileSync(outputPath, output);
console.log(`Generated ${outputPath}`);
