import {
  checkBelgianBBAN,
  checkCroatianBBAN,
  checkCzechAndSlovakBBAN,
  checkEstonianBBAN,
  checkFrenchBBAN,
  checkHungarianBBAN,
  checkMod9710BBAN,
  checkNorwayBBAN,
  checkPolandBBAN,
  checkSpainBBAN,
} from '../bban-validators';
import { type CountryMapInternal } from '../core/types';
import { registrySpecs } from './registry';

/**
 * Values the SWIFT IBAN Registry does not define, merged over the generated `registrySpecs`:
 * - national checksum validators (`bban_validation_func`)
 * - account number positions (`account_indentifier`, 0-based within the IBAN)
 * - countries and territories outside the registry, such as those covered by the FR and FI entries
 * - deliberate deviations: FR also has a branch identifier, and SI splits its bank code into bank and branch
 */
const overrides: CountryMapInternal = {
  AD: { account_indentifier: '12-23' },
  AE: { account_indentifier: '7-23' },
  AL: { account_indentifier: '12-28' },
  AO: { chars: 25, bban_regexp: '^[0-9]{21}$' },
  AX: { chars: 18, bban_regexp: '^[0-9]{14}$', IBANRegistry: true },
  AZ: { account_indentifier: '8-27' },
  BA: { bban_validation_func: checkMod9710BBAN },
  BE: { bban_validation_func: checkBelgianBBAN, account_indentifier: '7-13' },
  BF: { chars: 28, bban_regexp: '^[A-Z0-9]{2}[0-9]{22}$' },
  BH: { account_indentifier: '8-22' },
  BI: { account_indentifier: '14-27' },
  BJ: { chars: 28, bban_regexp: '^[A-Z0-9]{2}[0-9]{22}$' },
  BL: { chars: 27, bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$' },
  BR: { account_indentifier: '17-29' },
  CF: { chars: 27, bban_regexp: '^[0-9]{23}$' },
  CG: { chars: 27, bban_regexp: '^[0-9]{23}$' },
  CI: { chars: 28, bban_regexp: '^[A-Z]{1}[0-9]{23}$' },
  CM: { chars: 27, bban_regexp: '^[0-9]{23}$' },
  CR: { account_indentifier: '8-22' },
  CV: { chars: 25, bban_regexp: '^[0-9]{21}$' },
  CY: { account_indentifier: '12-28' },
  CZ: { bban_validation_func: checkCzechAndSlovakBBAN },
  DE: { account_indentifier: '12-21' },
  DJ: { account_indentifier: '14-27' },
  DK: { account_indentifier: '8-17' },
  DO: { account_indentifier: '8-28' },
  DZ: { chars: 26, bban_regexp: '^[0-9]{22}$' },
  EE: { bban_validation_func: checkEstonianBBAN, account_indentifier: '6-19' },
  EG: { account_indentifier: '12-28' },
  ES: { bban_validation_func: checkSpainBBAN, account_indentifier: '14-24' },
  FI: { account_indentifier: '7-17' },
  FK: { account_indentifier: '6-18' },
  FO: { account_indentifier: '8-17' },
  FR: { bban_validation_func: checkFrenchBBAN, branch_indentifier: '5-9', account_indentifier: '14-24' },
  GA: { chars: 27, bban_regexp: '^[0-9]{23}$' },
  GE: { account_indentifier: '6-22' },
  GF: { chars: 27, bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', IBANRegistry: true },
  GI: { account_indentifier: '8-23' },
  GL: { account_indentifier: '8-17' },
  GP: { chars: 27, bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', IBANRegistry: true },
  GQ: { chars: 27, bban_regexp: '^[0-9]{23}$' },
  GR: { account_indentifier: '11-26' },
  GT: { account_indentifier: '8-28' },
  GW: { chars: 25, bban_regexp: '^[A-Z]{2}[0-9]{19}$' },
  HN: { account_indentifier: '8-28' },
  HR: { bban_validation_func: checkCroatianBBAN },
  HU: { bban_validation_func: checkHungarianBBAN },
  IQ: { account_indentifier: '11-23' },
  IR: { chars: 26, bban_regexp: '^[0-9]{22}$' },
  IS: { account_indentifier: '8-25' },
  IT: { account_indentifier: '15-26' },
  KM: { chars: 27, bban_regexp: '^[0-9]{23}$' },
  KW: { account_indentifier: '8-29' },
  KZ: { account_indentifier: '7-19' },
  LB: { account_indentifier: '14-28' },
  LC: { account_indentifier: '8-32' },
  LV: { account_indentifier: '8-20' },
  LY: { account_indentifier: '10-25' },
  MA: { chars: 28, bban_regexp: '^[0-9]{24}$' },
  MC: { bban_validation_func: checkFrenchBBAN },
  MD: { account_indentifier: '6-24' },
  ME: { bban_validation_func: checkMod9710BBAN, account_indentifier: '7-19' },
  MF: { chars: 27, bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', IBANRegistry: true },
  MG: { chars: 27, bban_regexp: '^[0-9]{23}$' },
  MK: { bban_validation_func: checkMod9710BBAN },
  ML: { chars: 28, bban_regexp: '^[A-Z0-9]{2}[0-9]{22}$' },
  MN: { account_indentifier: '8-20' },
  MQ: { chars: 27, bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', IBANRegistry: true },
  MR: { account_indentifier: '14-24' },
  MT: { account_indentifier: '13-30' },
  MU: { account_indentifier: '12-23' },
  MZ: { chars: 25, bban_regexp: '^[0-9]{21}$' },
  NC: { chars: 27, bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', IBANRegistry: true },
  NE: { chars: 28, bban_regexp: '^[A-Z]{2}[0-9]{22}$' },
  NI: { account_indentifier: '8-28' },
  NL: { account_indentifier: '8-18' },
  NO: { bban_validation_func: checkNorwayBBAN, account_indentifier: '8-14' },
  PF: { chars: 27, bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', IBANRegistry: true },
  PL: { bban_validation_func: checkPolandBBAN, account_indentifier: '12-27' },
  PM: { chars: 27, bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', IBANRegistry: true },
  PS: { account_indentifier: '8-28' },
  PT: { bban_validation_func: checkMod9710BBAN },
  QA: { account_indentifier: '8-29' },
  RE: { chars: 27, bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', IBANRegistry: true },
  RO: { account_indentifier: '8-23' },
  RS: { bban_validation_func: checkMod9710BBAN },
  RU: { account_indentifier: '13-33' },
  SA: { account_indentifier: '6-23' },
  SC: { account_indentifier: '12-27' },
  SD: { account_indentifier: '6-18' },
  SI: {
    bban_validation_func: checkMod9710BBAN,
    bank_identifier: '0-1',
    branch_indentifier: '2-4',
    account_indentifier: '9-16',
  },
  SK: { bban_validation_func: checkCzechAndSlovakBBAN },
  SN: { chars: 28, bban_regexp: '^[A-Z]{2}[0-9]{22}$' },
  SO: { account_indentifier: '11-23' },
  SV: { account_indentifier: '8-28' },
  TD: { chars: 27, bban_regexp: '^[0-9]{23}$' },
  TF: { chars: 27, bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', IBANRegistry: true },
  TG: { chars: 28, bban_regexp: '^[A-Z]{2}[0-9]{22}$' },
  TL: { account_indentifier: '7-20' },
  TN: { account_indentifier: '9-21' },
  UA: { account_indentifier: '10-28' },
  VA: { account_indentifier: '7-22' },
  VG: { account_indentifier: '8-24' },
  WF: { chars: 27, bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', IBANRegistry: true },
  XK: { account_indentifier: '8-17' },
  YE: { account_indentifier: '12-30' },
  YT: { chars: 27, bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', IBANRegistry: true },
};

/**
 * IBAN format rules, BBAN validation, and SEPA membership for countries that use IBAN.
 */
export const ibanSpecs: CountryMapInternal = Object.fromEntries(
  [...new Set([...Object.keys(registrySpecs), ...Object.keys(overrides)])]
    .sort()
    .map((code) => [code, { ...registrySpecs[code], ...overrides[code] }]),
);
