import {
  checkBelgianBBAN,
  checkCroatianBBAN,
  checkCzechAndSlovakBBAN,
  checkEstonianBBAN,
  checkFrenchBBAN,
  checkHungarianBBAN,
  checkMod9710BBAN,
  checkNorwayBBAN,
  checkPolandBBAN,
  checkSpainBBAN,
} from '../bban-validators';
import { type CountryMapInternal } from '../core/types';

/**
 * IBAN format rules, BBAN validation, and SEPA membership for countries that use IBAN.
 */
export const ibanSpecs: CountryMapInternal = {
  AD: {
    chars: 24,
    bban_regexp: '^[0-9]{8}[A-Z0-9]{12}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '4-7',
    bank_identifier: '0-3',
    account_indentifier: '12-23',
  },
  AE: {
    chars: 23,
    bban_regexp: '^[0-9]{3}[0-9]{16}$',
    IBANRegistry: true,
    bank_identifier: '0-2',
    account_indentifier: '7-23',
  },
  AL: {
    chars: 28,
    bban_regexp: '^[0-9]{8}[A-Z0-9]{16}$',
    IBANRegistry: true,
    branch_indentifier: '3-7',
    bank_identifier: '0-2',
    account_indentifier: '12-28',
  },
  AO: {
    chars: 25,
    bban_regexp: '^[0-9]{21}$',
  },
  AT: { chars: 20, bban_regexp: '^[0-9]{16}$', IBANRegistry: true, SEPA: true, bank_identifier: '0-4' },
  AX: {
    chars: 18,
    bban_regexp: '^[0-9]{14}$',
    IBANRegistry: true,
  },
  AZ: {
    chars: 28,
    bban_regexp: '^[A-Z]{4}[A-Z0-9]{20}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-27',
  },
  BA: {
    chars: 20,
    bban_regexp: '^[0-9]{16}$',
    bban_validation_func: checkMod9710BBAN,
    IBANRegistry: true,
    branch_indentifier: '3-5',
    bank_identifier: '0-2',
  },
  BE: {
    chars: 16,
    bban_regexp: '^[0-9]{12}$',
    bban_validation_func: checkBelgianBBAN,
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-2',
    account_indentifier: '7-13',
  },
  BF: {
    chars: 28,
    bban_regexp: '^[A-Z0-9]{2}[0-9]{22}$',
  },
  BG: {
    chars: 22,
    bban_regexp: '^[A-Z]{4}[0-9]{6}[A-Z0-9]{8}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '4-7',
    bank_identifier: '0-3',
  },
  BH: {
    chars: 22,
    bban_regexp: '^[A-Z]{4}[A-Z0-9]{14}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-22',
  },
  BI: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
    IBANRegistry: true,
    branch_indentifier: '5-9',
    bank_identifier: '0-4',
    account_indentifier: '14-27',
  },
  BJ: {
    chars: 28,
    bban_regexp: '^[A-Z0-9]{2}[0-9]{22}$',
  },
  BL: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
  },
  BR: {
    chars: 29,
    bban_regexp: '^[A-Z0-9]{8}[0-9]{15}[A-Z0-9]{2}$',
    IBANRegistry: true,
    branch_indentifier: '8-12',
    bank_identifier: '0-7',
    account_indentifier: '17-29',
  },
  BY: {
    chars: 28,
    bban_regexp: '^[A-Z0-9]{4}[0-9]{4}[A-Z0-9]{16}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
  },
  CF: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
  },
  CG: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
  },
  CH: {
    chars: 21,
    bban_regexp: '^[0-9]{5}[A-Z0-9]{12}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-4',
  },
  CI: {
    chars: 28,
    bban_regexp: '^[A-Z]{1}[0-9]{23}$',
  },
  CM: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
  },
  CR: {
    chars: 22,
    bban_regexp: '^[0-9]{18}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-22',
  },
  CV: { chars: 25, bban_regexp: '^[0-9]{21}$' },
  CY: {
    chars: 28,
    bban_regexp: '^[0-9]{8}[A-Z0-9]{16}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '3-7',
    bank_identifier: '0-2',
    account_indentifier: '12-28',
  },
  CZ: {
    chars: 24,
    bban_regexp: '^[0-9]{20}$',
    bban_validation_func: checkCzechAndSlovakBBAN,
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-3',
  },
  DE: {
    chars: 22,
    bban_regexp: '^[0-9]{18}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-7',
    account_indentifier: '12-21',
  },
  DJ: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
    IBANRegistry: true,
    branch_indentifier: '5-9',
    bank_identifier: '0-4',
    account_indentifier: '14-27',
  },
  DK: {
    chars: 18,
    bban_regexp: '^[0-9]{14}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-3',
    account_indentifier: '8-17',
  },
  DO: {
    chars: 28,
    bban_regexp: '^[A-Z0-9]{4}[0-9]{20}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-28',
  },
  DZ: {
    chars: 26,
    bban_regexp: '^[0-9]{22}$',
  },
  EE: {
    chars: 20,
    bban_regexp: '^[0-9]{16}$',
    bban_validation_func: checkEstonianBBAN,
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-1',
    account_indentifier: '6-19',
  },
  EG: {
    chars: 29,
    bban_regexp: '^[0-9]{25}$',
    IBANRegistry: true,
    branch_indentifier: '4-7',
    bank_identifier: '0-3',
    account_indentifier: '12-28',
  },
  ES: {
    chars: 24,
    bban_validation_func: checkSpainBBAN,
    bban_regexp: '^[0-9]{20}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '4-7',
    bank_identifier: '0-3',
    account_indentifier: '14-24',
  },
  FI: {
    chars: 18,
    bban_regexp: '^[0-9]{14}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-2',
    account_indentifier: '7-17',
  },
  FK: {
    chars: 18,
    bban_regexp: '^[A-Z]{2}[0-9]{12}$',
    IBANRegistry: true,
    bank_identifier: '0-1',
    account_indentifier: '6-18',
  },
  FO: {
    chars: 18,
    bban_regexp: '^[0-9]{14}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-17',
  },
  FR: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    bban_validation_func: checkFrenchBBAN,
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-4',
    branch_indentifier: '5-9',
    account_indentifier: '14-24',
  },
  GA: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
  },
  GB: {
    chars: 22,
    bban_regexp: '^[A-Z]{4}[0-9]{14}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '4-9',
    bank_identifier: '0-3',
  },
  GE: {
    chars: 22,
    bban_regexp: '^[A-Z]{2}[0-9]{16}$',
    IBANRegistry: true,
    bank_identifier: '0-1',
    account_indentifier: '6-22',
  },
  GF: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  GI: {
    chars: 23,
    bban_regexp: '^[A-Z]{4}[A-Z0-9]{15}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-3',
    account_indentifier: '8-23',
  },
  GL: {
    chars: 18,
    bban_regexp: '^[0-9]{14}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-17',
  },
  GP: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  GQ: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
  },
  GR: {
    chars: 27,
    bban_regexp: '^[0-9]{7}[A-Z0-9]{16}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '3-6',
    bank_identifier: '0-2',
    account_indentifier: '11-26',
  },
  GT: {
    chars: 28,
    bban_regexp: '^[A-Z0-9]{24}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-28',
  },
  GW: {
    chars: 25,
    bban_regexp: '^[A-Z]{2}[0-9]{19}$',
  },
  HN: {
    chars: 28,
    bban_regexp: '^[A-Z]{4}[0-9]{20}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-28',
  },
  HR: {
    chars: 21,
    bban_regexp: '^[0-9]{17}$',
    bban_validation_func: checkCroatianBBAN,
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-6',
  },
  HU: {
    chars: 28,
    bban_regexp: '^[0-9]{24}$',
    bban_validation_func: checkHungarianBBAN,
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '3-6',
    bank_identifier: '0-2',
  },
  IE: {
    chars: 22,
    bban_regexp: '^[A-Z]{4}[0-9]{14}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '4-9',
    bank_identifier: '0-3',
  },
  IL: {
    chars: 23,
    bban_regexp: '^[0-9]{19}$',
    IBANRegistry: true,
    branch_indentifier: '3-5',
    bank_identifier: '0-2',
  },
  IQ: {
    chars: 23,
    bban_regexp: '^[A-Z]{4}[0-9]{15}$',
    IBANRegistry: true,
    branch_indentifier: '4-6',
    bank_identifier: '0-3',
    account_indentifier: '11-23',
  },
  IR: {
    chars: 26,
    bban_regexp: '^[0-9]{22}$',
  },
  IS: {
    chars: 26,
    bban_regexp: '^[0-9]{22}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '2-3',
    bank_identifier: '0-1',
    account_indentifier: '8-25',
  },
  IT: {
    chars: 27,
    bban_regexp: '^[A-Z]{1}[0-9]{10}[A-Z0-9]{12}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '6-10',
    bank_identifier: '1-5',
    account_indentifier: '15-26',
  },
  JO: {
    chars: 30,
    bban_regexp: '^[A-Z]{4}[0-9]{4}[A-Z0-9]{18}$',
    IBANRegistry: true,
    branch_indentifier: '4-7',
    bank_identifier: '0-3',
  },
  KM: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
  },
  KW: {
    chars: 30,
    bban_regexp: '^[A-Z]{4}[A-Z0-9]{22}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-29',
  },
  KZ: {
    chars: 20,
    bban_regexp: '^[0-9]{3}[A-Z0-9]{13}$',
    IBANRegistry: true,
    bank_identifier: '0-2',
    account_indentifier: '7-19',
  },
  LB: {
    chars: 28,
    bban_regexp: '^[0-9]{4}[A-Z0-9]{20}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '14-28',
  },
  LC: {
    chars: 32,
    bban_regexp: '^[A-Z]{4}[A-Z0-9]{24}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-32',
  },
  LI: {
    chars: 21,
    bban_regexp: '^[0-9]{5}[A-Z0-9]{12}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-4',
  },
  LT: { chars: 20, bban_regexp: '^[0-9]{16}$', IBANRegistry: true, SEPA: true, bank_identifier: '0-4' },
  LU: {
    chars: 20,
    bban_regexp: '^[0-9]{3}[A-Z0-9]{13}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-2',
  },
  LV: {
    chars: 21,
    bban_regexp: '^[A-Z]{4}[A-Z0-9]{13}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-3',
    account_indentifier: '8-20',
  },
  LY: {
    chars: 25,
    bban_regexp: '^[0-9]{21}$',
    IBANRegistry: true,
    branch_indentifier: '3-5',
    bank_identifier: '0-2',
    account_indentifier: '10-25',
  },
  MA: {
    chars: 28,
    bban_regexp: '^[0-9]{24}$',
  },
  MC: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    bban_validation_func: checkFrenchBBAN,
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '5-9',
    bank_identifier: '0-4',
  },
  MD: {
    chars: 24,
    bban_regexp: '^[A-Z0-9]{2}[A-Z0-9]{18}$',
    IBANRegistry: true,
    bank_identifier: '0-1',
    account_indentifier: '6-24',
  },
  ME: {
    chars: 22,
    bban_regexp: '^[0-9]{18}$',
    bban_validation_func: checkMod9710BBAN,
    IBANRegistry: true,
    bank_identifier: '0-2',
    account_indentifier: '7-19',
  },
  MF: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  MG: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
  },
  MK: {
    chars: 19,
    bban_regexp: '^[0-9]{3}[A-Z0-9]{10}[0-9]{2}$',
    bban_validation_func: checkMod9710BBAN,
    IBANRegistry: true,
    bank_identifier: '0-2',
  },
  ML: {
    chars: 28,
    bban_regexp: '^[A-Z0-9]{2}[0-9]{22}$',
  },
  MN: {
    chars: 20,
    bban_regexp: '^[0-9]{16}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-20',
  },
  MQ: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  MR: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
    IBANRegistry: true,
    branch_indentifier: '5-9',
    bank_identifier: '0-4',
    account_indentifier: '14-24',
  },
  MT: {
    chars: 31,
    bban_regexp: '^[A-Z]{4}[0-9]{5}[A-Z0-9]{18}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '4-8',
    bank_identifier: '0-3',
    account_indentifier: '13-30',
  },
  MU: {
    chars: 30,
    bban_regexp: '^[A-Z]{4}[0-9]{19}[A-Z]{3}$',
    IBANRegistry: true,
    branch_indentifier: '6-7',
    bank_identifier: '0-5',
    account_indentifier: '12-23',
  },
  MZ: {
    chars: 25,
    bban_regexp: '^[0-9]{21}$',
  },
  NC: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  NE: {
    chars: 28,
    bban_regexp: '^[A-Z]{2}[0-9]{22}$',
  },
  NI: {
    chars: 28,
    bban_regexp: '^[A-Z]{4}[0-9]{20}$',
    bank_identifier: '0-3',
    IBANRegistry: true,
    account_indentifier: '8-28',
  },
  NL: {
    chars: 18,
    bban_regexp: '^[A-Z]{4}[0-9]{10}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-3',
    account_indentifier: '8-18',
  },
  NO: {
    chars: 15,
    bban_regexp: '^[0-9]{11}$',
    bban_validation_func: checkNorwayBBAN,
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-3',
    account_indentifier: '8-14',
  },
  OM: {
    chars: 23,
    bban_regexp: '^[0-9]{3}[A-Z0-9]{16}$',
    IBANRegistry: true,
    SEPA: false,
    bank_identifier: '0-2',
  },
  PF: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  PK: {
    chars: 24,
    bban_regexp: '^[A-Z]{4}[A-Z0-9]{16}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
  },
  PL: {
    chars: 28,
    bban_validation_func: checkPolandBBAN,
    bban_regexp: '^[0-9]{24}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-7',
    account_indentifier: '12-27',
  },
  PM: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  PS: {
    chars: 29,
    bban_regexp: '^[A-Z]{4}[A-Z0-9]{21}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-28',
  },
  PT: {
    chars: 25,
    bban_regexp: '^[0-9]{21}$',
    bban_validation_func: checkMod9710BBAN,
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-3',
  },
  QA: {
    chars: 29,
    bban_regexp: '^[A-Z]{4}[A-Z0-9]{21}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-29',
  },
  RE: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  RO: {
    chars: 24,
    bban_regexp: '^[A-Z]{4}[A-Z0-9]{16}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-3',
    account_indentifier: '8-23',
  },
  RS: {
    chars: 22,
    bban_regexp: '^[0-9]{18}$',
    bban_validation_func: checkMod9710BBAN,
    IBANRegistry: true,
    bank_identifier: '0-2',
  },
  RU: {
    chars: 33,
    bban_regexp: '^[0-9]{14}[A-Z0-9]{15}$',
    IBANRegistry: true,
    branch_indentifier: '9-13',
    bank_identifier: '0-8',
    account_indentifier: '13-33',
  },
  SA: {
    chars: 24,
    bban_regexp: '^[0-9]{2}[A-Z0-9]{18}$',
    IBANRegistry: true,
    bank_identifier: '0-1',
    account_indentifier: '6-23',
  },
  SC: {
    chars: 31,
    bban_regexp: '^[A-Z]{4}[0-9]{20}[A-Z]{3}$',
    IBANRegistry: true,
    branch_indentifier: '6-7',
    bank_identifier: '0-5',
    account_indentifier: '12-27',
  },
  SD: {
    chars: 18,
    bban_regexp: '^[0-9]{14}$',
    IBANRegistry: true,
    bank_identifier: '0-1',
    account_indentifier: '6-18',
  },
  SE: { chars: 24, bban_regexp: '^[0-9]{20}$', IBANRegistry: true, SEPA: true, bank_identifier: '0-2' },
  SI: {
    chars: 19,
    bban_regexp: '^[0-9]{15}$',
    bban_validation_func: checkMod9710BBAN,
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '2-4',
    bank_identifier: '0-1',
    account_indentifier: '9-16',
  },
  SK: {
    chars: 24,
    bban_regexp: '^[0-9]{20}$',
    bban_validation_func: checkCzechAndSlovakBBAN,
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-3',
  },
  SM: {
    chars: 27,
    bban_regexp: '^[A-Z]{1}[0-9]{10}[A-Z0-9]{12}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '6-10',
    bank_identifier: '1-5',
  },
  SN: {
    chars: 28,
    bban_regexp: '^[A-Z]{2}[0-9]{22}$',
  },
  SO: {
    chars: 23,
    bban_regexp: '^[0-9]{19}$',
    IBANRegistry: true,
    branch_indentifier: '4-6',
    account_indentifier: '11-23',
    bank_identifier: '0-3',
  },
  ST: {
    chars: 25,
    bban_regexp: '^[0-9]{21}$',
    IBANRegistry: true,
    branch_indentifier: '4-7',
    bank_identifier: '0-3',
  },
  SV: {
    chars: 28,
    bban_regexp: '^[A-Z]{4}[0-9]{20}$',
    IBANRegistry: true,
    account_indentifier: '8-28',
    bank_identifier: '0-3',
  },
  TD: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
  },
  TF: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  TG: {
    chars: 28,
    bban_regexp: '^[A-Z]{2}[0-9]{22}$',
  },
  TL: {
    chars: 23,
    bban_regexp: '^[0-9]{19}$',
    IBANRegistry: true,
    account_indentifier: '7-20',
    bank_identifier: '0-2',
  },
  TN: {
    chars: 24,
    bban_regexp: '^[0-9]{20}$',
    IBANRegistry: true,
    branch_indentifier: '2-4',
    account_indentifier: '9-21',
    bank_identifier: '0-1',
  },
  TR: {
    chars: 26,
    bban_regexp: '^[0-9]{6}[A-Z0-9]{16}$',
    IBANRegistry: true,
    bank_identifier: '0-4',
  },
  UA: {
    chars: 29,
    bban_regexp: '^[0-9]{6}[A-Z0-9]{19}$',
    IBANRegistry: true,
    account_indentifier: '10-28',
    bank_identifier: '0-5',
  },
  VA: {
    chars: 22,
    bban_regexp: '^[0-9]{18}$',
    IBANRegistry: true,
    SEPA: true,
    account_indentifier: '7-22',
    bank_identifier: '0-2',
  },
  VG: {
    chars: 24,
    bban_regexp: '^[A-Z]{4}[0-9]{16}$',
    IBANRegistry: true,
    account_indentifier: '8-24',
    bank_identifier: '0-3',
  },
  WF: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  XK: {
    chars: 20,
    bban_regexp: '^[0-9]{16}$',
    IBANRegistry: true,
    branch_indentifier: '2-3',
    account_indentifier: '8-17',
    bank_identifier: '0-1',
  },
  YE: {
    chars: 30,
    bban_regexp: '^[A-Z]{4}[0-9]{4}[A-Z0-9]{18}$',
    IBANRegistry: true,
    branch_indentifier: '4-7',
    bank_identifier: '0-3',
    account_indentifier: '12-30',
  },
  YT: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
};
