/*!
 * @license
 * Licensed under the Mozilla Public License, Version 2.0 or the MIT license,
 * at your option.
 * SPDX-License-Identifier: MIT or MPL/2.0
 */

import {
  checkBelgianBBAN,
  checkCroatianBBAN,
  checkCzechAndSlovakBBAN,
  checkEstonianBBAN,
  checkFrenchBBAN,
  checkHungarianBBAN,
  checkMod9710BBAN,
  checkNorwayBBAN,
  checkPolandBBAN,
  checkSpainBBAN,
} from '../bban-validators';
import { type CountryMapInternal } from '../core/types';

/**
 * Country specifications for all countries (249 total)
 * Contains IBAN format rules, BBAN validation, and SEPA membership
 */
export const countrySpecs: CountryMapInternal = {
  AD: {
    chars: 24,
    bban_regexp: '^[0-9]{8}[A-Z0-9]{12}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '4-7',
    bank_identifier: '0-3',
    account_indentifier: '8-24',
  },
  AE: {
    chars: 23,
    bban_regexp: '^[0-9]{3}[0-9]{16}$',
    IBANRegistry: true,
    bank_identifier: '0-2',
    account_indentifier: '7-23',
  },
  AF: {},
  AG: {},
  AI: {},
  AL: {
    chars: 28,
    bban_regexp: '^[0-9]{8}[A-Z0-9]{16}$',
    IBANRegistry: true,
    branch_indentifier: '3-7',
    bank_identifier: '0-2',
    account_indentifier: '12-28',
  },
  AM: {},
  AO: {
    chars: 25,
    bban_regexp: '^[0-9]{21}$',
  },
  AQ: {},
  AR: {},
  AS: {},
  AT: { chars: 20, bban_regexp: '^[0-9]{16}$', IBANRegistry: true, SEPA: true, bank_identifier: '0-4' },
  AU: {},
  AW: {},
  AX: {
    chars: 18,
    bban_regexp: '^[0-9]{14}$',
    IBANRegistry: true,
  },
  AZ: {
    chars: 28,
    bban_regexp: '^[A-Z]{4}[A-Z0-9]{20}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '4-28',
  },
  BA: {
    chars: 20,
    bban_regexp: '^[0-9]{16}$',
    bban_validation_func: checkMod9710BBAN,
    IBANRegistry: true,
    branch_indentifier: '3-5',
    bank_identifier: '0-2',
  },
  BB: {},
  BD: {},
  BE: {
    chars: 16,
    bban_regexp: '^[0-9]{12}$',
    bban_validation_func: checkBelgianBBAN,
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-2',
    account_indentifier: '0-16',
  },
  BF: {
    chars: 28,
    bban_regexp: '^[A-Z0-9]{2}[0-9]{22}$',
  },
  BG: {
    chars: 22,
    bban_regexp: '^[A-Z]{4}[0-9]{6}[A-Z0-9]{8}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '4-7',
    bank_identifier: '0-3',
  },
  BH: {
    chars: 22,
    bban_regexp: '^[A-Z]{4}[A-Z0-9]{14}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-22',
  },
  BI: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
    branch_indentifier: '5-9',
    bank_identifier: '0-4',
    account_indentifier: '14-27',
  },
  BJ: {
    chars: 28,
    bban_regexp: '^[A-Z0-9]{2}[0-9]{22}$',
  },
  BL: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
  },
  BM: {},
  BN: {},
  BO: {},
  BQ: {},
  BR: {
    chars: 29,
    bban_regexp: '^[0-9]{23}[A-Z]{1}[A-Z0-9]{1}$',
    IBANRegistry: true,
    branch_indentifier: '8-12',
    bank_identifier: '0-7',
    account_indentifier: '17-29',
  },
  BS: {},
  BT: {},
  BV: {},
  BW: {},
  BY: {
    chars: 28,
    bban_regexp: '^[A-Z]{4}[0-9]{4}[A-Z0-9]{16}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
  },
  BZ: {},
  CA: {},
  CC: {},
  CD: {},
  CF: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
  },
  CG: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
  },
  CH: {
    chars: 21,
    bban_regexp: '^[0-9]{5}[A-Z0-9]{12}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-4',
  },
  CI: {
    chars: 28,
    bban_regexp: '^[A-Z]{1}[0-9]{23}$',
  },
  CK: {},
  CL: {},
  CM: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
  },
  CN: {},
  CO: {},
  CR: {
    chars: 22,
    bban_regexp: '^[0-9]{18}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-22',
  },
  CU: {},
  CV: { chars: 25, bban_regexp: '^[0-9]{21}$' },
  CW: {},
  CX: {},
  CY: {
    chars: 28,
    bban_regexp: '^[0-9]{8}[A-Z0-9]{16}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '3-7',
    bank_identifier: '0-2',
    account_indentifier: '12-28',
  },
  CZ: {
    chars: 24,
    bban_regexp: '^[0-9]{20}$',
    bban_validation_func: checkCzechAndSlovakBBAN,
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-3',
  },
  DE: {
    chars: 22,
    bban_regexp: '^[0-9]{18}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-7',
    account_indentifier: '13-22',
  },
  DJ: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
    branch_indentifier: '5-9',
    bank_identifier: '0-4',
    account_indentifier: '14-27',
  },
  DK: {
    chars: 18,
    bban_regexp: '^[0-9]{14}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-3',
    account_indentifier: '4-18',
  },
  DM: {},
  DO: {
    chars: 28,
    bban_regexp: '^[A-Z]{4}[0-9]{20}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-28',
  },
  DZ: {
    chars: 26,
    bban_regexp: '^[0-9]{22}$',
  },
  EC: {},
  EE: {
    chars: 20,
    bban_regexp: '^[0-9]{16}$',
    bban_validation_func: checkEstonianBBAN,
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-1',
    account_indentifier: '8-20',
  },
  EG: {
    chars: 29,
    bban_regexp: '^[0-9]{25}',
    IBANRegistry: true,
    branch_indentifier: '4-7',
    bank_identifier: '0-3',
    account_indentifier: '17-29',
  },
  EH: {},
  ER: {},
  ES: {
    chars: 24,
    bban_validation_func: checkSpainBBAN,
    bban_regexp: '^[0-9]{20}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '4-7',
    bank_identifier: '0-3',
    account_indentifier: '14-24',
  },
  ET: {},
  FI: {
    chars: 18,
    bban_regexp: '^[0-9]{14}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-2',
    account_indentifier: '0-0',
  },
  FJ: {},
  FK: {
    chars: 18,
    bban_regexp: '^[A-Z]{2}[0-9]{12}$',
    bank_identifier: '0-1',
    account_indentifier: '6-18',
  },
  FM: {},
  FO: {
    chars: 18,
    bban_regexp: '^[0-9]{14}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '4-18',
  },
  FR: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    bban_validation_func: checkFrenchBBAN,
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-4',
    branch_indentifier: '5-9',
    account_indentifier: '14-24',
  },
  GA: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
  },
  GB: {
    chars: 22,
    bban_regexp: '^[A-Z]{4}[0-9]{14}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '4-9',
    bank_identifier: '0-3',
  },
  GD: {},
  GE: {
    chars: 22,
    bban_regexp: '^[A-Z0-9]{2}[0-9]{16}$',
    IBANRegistry: true,
    bank_identifier: '0-1',
    account_indentifier: '6-22',
  },
  GF: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  GG: {},
  GH: {},
  GI: {
    chars: 23,
    bban_regexp: '^[A-Z]{4}[A-Z0-9]{15}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-3',
    account_indentifier: '8-23',
  },
  GL: {
    chars: 18,
    bban_regexp: '^[0-9]{14}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '4-18',
  },
  GM: {},
  GN: {},
  GP: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  GQ: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
  },
  GR: {
    chars: 27,
    bban_regexp: '^[0-9]{7}[A-Z0-9]{16}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '3-6',
    bank_identifier: '0-2',
    account_indentifier: '7-27',
  },
  GS: {},
  GT: {
    chars: 28,
    bban_regexp: '^[A-Z0-9]{24}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-28',
  },
  GU: {},
  GW: {
    chars: 25,
    bban_regexp: '^[A-Z]{2}[0-9]{19}$',
  },
  GY: {},
  HK: {},
  HM: {},
  HN: {
    chars: 28,
    bban_regexp: '^[A-Z]{4}[0-9]{20}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-28',
  },
  HR: {
    chars: 21,
    bban_regexp: '^[0-9]{17}$',
    bban_validation_func: checkCroatianBBAN,
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-6',
  },
  HT: {},
  HU: {
    chars: 28,
    bban_regexp: '^[0-9]{24}$',
    bban_validation_func: checkHungarianBBAN,
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '3-6',
    bank_identifier: '0-2',
  },
  ID: {},
  IE: {
    chars: 22,
    bban_regexp: '^[A-Z0-9]{4}[0-9]{14}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '4-9',
    bank_identifier: '0-3',
  },
  IL: {
    chars: 23,
    bban_regexp: '^[0-9]{19}$',
    IBANRegistry: true,
    branch_indentifier: '3-5',
    bank_identifier: '0-2',
  },
  IM: {},
  IN: {},
  IO: {},
  IQ: {
    chars: 23,
    bban_regexp: '^[A-Z]{4}[0-9]{15}$',
    IBANRegistry: true,
    branch_indentifier: '4-6',
    bank_identifier: '0-3',
    account_indentifier: '11-23',
  },
  IR: {
    chars: 26,
    bban_regexp: '^[0-9]{22}$',
  },
  IS: {
    chars: 26,
    bban_regexp: '^[0-9]{22}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '2-3',
    bank_identifier: '0-1',
  },
  IT: {
    chars: 27,
    bban_regexp: '^[A-Z]{1}[0-9]{10}[A-Z0-9]{12}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '6-10',
    bank_identifier: '1-5',
    account_indentifier: '4-27',
  },
  JE: {},
  JM: {},
  JO: {
    chars: 30,
    bban_regexp: '^[A-Z]{4}[0-9]{4}[A-Z0-9]{18}$',
    IBANRegistry: true,
    branch_indentifier: '4-7',
    bank_identifier: '0-3',
  },
  JP: {},
  KE: {},
  KG: {},
  KH: {},
  KI: {},
  KM: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
  },
  KN: {},
  KP: {},
  KR: {},
  KW: {
    chars: 30,
    bban_regexp: '^[A-Z]{4}[A-Z0-9]{22}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '20-30',
  },
  KY: {},
  KZ: {
    chars: 20,
    bban_regexp: '^[0-9]{3}[A-Z0-9]{13}$',
    IBANRegistry: true,
    bank_identifier: '0-2',
    account_indentifier: '0-20',
  },
  LA: {},
  LB: {
    chars: 28,
    bban_regexp: '^[0-9]{4}[A-Z0-9]{20}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '14-28',
  },
  LC: {
    chars: 32,
    bban_regexp: '^[A-Z]{4}[A-Z0-9]{24}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-32',
  },
  LI: {
    chars: 21,
    bban_regexp: '^[0-9]{5}[A-Z0-9]{12}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-4',
  },
  LK: {},
  LR: {},
  LS: {},
  LT: { chars: 20, bban_regexp: '^[0-9]{16}$', IBANRegistry: true, SEPA: true, bank_identifier: '0-4' },
  LU: {
    chars: 20,
    bban_regexp: '^[0-9]{3}[A-Z0-9]{13}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-2',
  },
  LV: {
    chars: 21,
    bban_regexp: '^[A-Z]{4}[A-Z0-9]{13}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-3',
    account_indentifier: '0-21',
  },
  LY: {
    chars: 25,
    bban_regexp: '^[0-9]{21}$',
    IBANRegistry: true,
    branch_indentifier: '3-5',
    bank_identifier: '0-2',
    account_indentifier: '10-25',
  },
  MA: {
    chars: 28,
    bban_regexp: '^[0-9]{24}$',
  },
  MC: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    bban_validation_func: checkFrenchBBAN,
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '5-9',
    bank_identifier: '0-4',
  },
  MD: {
    chars: 24,
    bban_regexp: '^[A-Z0-9]{2}[A-Z0-9]{18}$',
    IBANRegistry: true,
    bank_identifier: '0-1',
    account_indentifier: '6-24',
  },
  ME: {
    chars: 22,
    bban_regexp: '^[0-9]{18}$',
    bban_validation_func: checkMod9710BBAN,
    IBANRegistry: true,
    bank_identifier: '0-2',
    account_indentifier: '4-22',
  },
  MF: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  MG: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
  },
  MH: {},
  MK: {
    chars: 19,
    bban_regexp: '^[0-9]{3}[A-Z0-9]{10}[0-9]{2}$',
    bban_validation_func: checkMod9710BBAN,
    IBANRegistry: true,
    bank_identifier: '0-2',
  },
  ML: {
    chars: 28,
    bban_regexp: '^[A-Z0-9]{2}[0-9]{22}$',
  },
  MM: {},
  MN: {
    chars: 20,
    bban_regexp: '^[0-9]{16}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-20',
  },
  MO: {},
  MP: {},
  MQ: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  MR: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
    IBANRegistry: true,
    branch_indentifier: '5-9',
    bank_identifier: '0-4',
    account_indentifier: '4-27',
  },
  MS: {},
  MT: {
    chars: 31,
    bban_regexp: '^[A-Z]{4}[0-9]{5}[A-Z0-9]{18}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '4-8',
    bank_identifier: '0-3',
    account_indentifier: '15-31',
  },
  MU: {
    chars: 30,
    bban_regexp: '^[A-Z]{4}[0-9]{19}[A-Z]{3}$',
    IBANRegistry: true,
    branch_indentifier: '6-7',
    bank_identifier: '0-5',
    account_indentifier: '0-30',
  },
  MV: {},
  MW: {},
  MX: {},
  MY: {},
  MZ: {
    chars: 25,
    bban_regexp: '^[0-9]{21}$',
  },
  NA: {},
  NC: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  NE: {
    chars: 28,
    bban_regexp: '^[A-Z]{2}[0-9]{22}$',
  },
  NF: {},
  NG: {},
  NI: {
    chars: 28,
    bban_regexp: '^[A-Z]{4}[0-9]{20}$',
    bank_identifier: '0-3',
    IBANRegistry: true,
    account_indentifier: '8-28',
  },
  NL: {
    chars: 18,
    bban_regexp: '^[A-Z]{4}[0-9]{10}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-3',
    account_indentifier: '8-18',
  },
  NO: {
    chars: 15,
    bban_regexp: '^[0-9]{11}$',
    bban_validation_func: checkNorwayBBAN,
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-3',
    account_indentifier: '4-15',
  },
  NP: {},
  NR: {},
  NU: {},
  NZ: {},
  OM: {
    chars: 23,
    bban_regexp: '^[0-9]{3}[A-Z0-9]{16}$',
    IBANRegistry: true,
    SEPA: false,
    bank_identifier: '0-2',
  },
  PA: {},
  PE: {},
  PF: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  PG: {},
  PH: {},
  PK: {
    chars: 24,
    bban_regexp: '^[A-Z0-9]{4}[0-9]{16}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
  },
  PL: {
    chars: 28,
    bban_validation_func: checkPolandBBAN,
    bban_regexp: '^[0-9]{24}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '0-7',
    account_indentifier: '2-28',
  },
  PM: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  PN: {},
  PR: {},
  PS: {
    chars: 29,
    bban_regexp: '^[A-Z0-9]{4}[0-9]{21}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '17-29',
  },
  PT: {
    chars: 25,
    bban_regexp: '^[0-9]{21}$',
    bban_validation_func: checkMod9710BBAN,
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-3',
  },
  PW: {},
  PY: {},
  QA: {
    chars: 29,
    bban_regexp: '^[A-Z]{4}[A-Z0-9]{21}$',
    IBANRegistry: true,
    bank_identifier: '0-3',
    account_indentifier: '8-29',
  },
  RE: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  RO: {
    chars: 24,
    bban_regexp: '^[A-Z]{4}[A-Z0-9]{16}$',
    IBANRegistry: true,
    SEPA: true,
    bank_identifier: '0-3',
    account_indentifier: '0-24',
  },
  RS: {
    chars: 22,
    bban_regexp: '^[0-9]{18}$',
    bban_validation_func: checkMod9710BBAN,
    IBANRegistry: true,
    bank_identifier: '0-2',
  },
  RU: {
    chars: 33,
    bban_regexp: '^[0-9]{14}[A-Z0-9]{15}$',
    IBANRegistry: true,
    branch_indentifier: '9-13',
    bank_identifier: '0-8',
    account_indentifier: '13-33',
  },
  RW: {},
  SA: {
    chars: 24,
    bban_regexp: '^[0-9]{2}[A-Z0-9]{18}$',
    IBANRegistry: true,
    bank_identifier: '0-1',
    account_indentifier: '12-24',
  },
  SB: {},
  SC: {
    chars: 31,
    bban_regexp: '^[A-Z]{4}[0-9]{20}[A-Z]{3}$',
    IBANRegistry: true,
    branch_indentifier: '6-7',
    bank_identifier: '0-5',
    account_indentifier: '12-28',
  },
  SD: {
    chars: 18,
    bban_regexp: '^[0-9]{14}$',
    IBANRegistry: true,
    bank_identifier: '0-1',
    account_indentifier: '6-18',
  },
  SE: { chars: 24, bban_regexp: '^[0-9]{20}$', IBANRegistry: true, SEPA: true, bank_identifier: '0-2' },
  SG: {},
  SH: {},
  SI: {
    chars: 19,
    bban_regexp: '^[0-9]{15}$',
    bban_validation_func: checkMod9710BBAN,
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '2-4',
    bank_identifier: '0-1',
    account_indentifier: '9-16',
  },
  SJ: {},
  SK: {
    chars: 24,
    bban_regexp: '^[0-9]{20}$',
    bban_validation_func: checkCzechAndSlovakBBAN,
    IBANRegistry: true,
    SEPA: true,
  },
  SL: {},
  SM: {
    chars: 27,
    bban_regexp: '^[A-Z]{1}[0-9]{10}[A-Z0-9]{12}$',
    IBANRegistry: true,
    SEPA: true,
    branch_indentifier: '6-10',
  },
  SN: {
    chars: 28,
    bban_regexp: '^[A-Z]{2}[0-9]{22}$',
  },
  SO: {
    chars: 23,
    bban_regexp: '^[0-9]{19}$',
    IBANRegistry: true,
    branch_indentifier: '4-6',
    account_indentifier: '11-23',
  },
  SR: {},
  SS: {},
  ST: {
    chars: 25,
    bban_regexp: '^[0-9]{21}$',
    IBANRegistry: true,
    branch_indentifier: '4-7',
  },
  SV: {
    chars: 28,
    bban_regexp: '^[A-Z]{4}[0-9]{20}$',
    IBANRegistry: true,
    account_indentifier: '8-28',
  },
  SX: {},
  SY: {},
  SZ: {},
  TC: {},
  TD: {
    chars: 27,
    bban_regexp: '^[0-9]{23}$',
  },
  TF: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  TG: {
    chars: 28,
    bban_regexp: '^[A-Z]{2}[0-9]{22}$',
  },
  TH: {},
  TJ: {},
  TK: {},
  TL: {
    chars: 23,
    bban_regexp: '^[0-9]{19}$',
    IBANRegistry: true,
    account_indentifier: '4-23',
  },
  TM: {},
  TN: {
    chars: 24,
    bban_regexp: '^[0-9]{20}$',
    IBANRegistry: true,
    branch_indentifier: '2-4',
    account_indentifier: '4-24',
  },
  TO: {},
  TR: {
    chars: 26,
    bban_regexp: '^[0-9]{5}[A-Z0-9]{17}$',
    IBANRegistry: true,
  },
  TT: {},
  TV: {},
  TW: {},
  TZ: {},
  UA: {
    chars: 29,
    bban_regexp: '^[0-9]{6}[A-Z0-9]{19}$',
    IBANRegistry: true,
    account_indentifier: '15-29',
  },
  UG: {},
  UM: {},
  US: {},
  UY: {},
  UZ: {},
  VA: {
    chars: 22,
    bban_regexp: '^[0-9]{18}',
    IBANRegistry: true,
    SEPA: true,
    account_indentifier: '7-22',
  },
  VC: {},
  VE: {},
  VG: {
    chars: 24,
    bban_regexp: '^[A-Z0-9]{4}[0-9]{16}$',
    IBANRegistry: true,
    account_indentifier: '8-24',
  },
  VI: {},
  VN: {},
  VU: {},
  WF: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  WS: {},
  XK: {
    chars: 20,
    bban_regexp: '^[0-9]{16}$',
    IBANRegistry: true,
    branch_indentifier: '2-3',
    account_indentifier: '4-20',
  },
  YE: {
    chars: 30,
    bban_regexp: '^[A-Z]{4}[0-9]{4}[A-Z0-9]{18}$',
    IBANRegistry: true,
    branch_indentifier: '4-7',
    bank_identifier: '0-3',
    account_indentifier: '12-30',
  },
  YT: {
    chars: 27,
    bban_regexp: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$',
    IBANRegistry: true,
  },
  ZA: {},
  ZM: {},
  ZW: {},
};
